export const SET_ACTIVE_DESK_CARD = "SET_ACTIVE_DESK_CARD";
export const PICK_CARD = "PICK_CARD";
export const RESET_CARDS = "RESET_CARDS";

export const RANDOMIZE_BOARD = "RANDOMIZE_BOARD";
export const CLEAR_BOARD = "CLEAR_BOARD";